### PR TITLE
Added handling of multi-case switch statements

### PR DESCRIPTION
**Pull request by ruaanvds**
See https://github.com/chiquitinxx/grooscript/issues/59

### CODE REVIEW

**Comment by ruaanvds** [comment]
@chiquitinxx Took a stab at this last night. Not sure why the Travis CI build is failing, though?

**Comment by chiquitinxx** [comment]
Ill take a look later, sometimes java8 fails in travis

**Comment by chiquitinxx** [comment]
Very nice, thank you very much!

**Comment by ruaanvds** [comment]
@chiquitinxx My pleasure. Looking forward to contributing some more.

**Pull request merged**
